-- Free Pool Radar — core intelligence schema.
--
-- Design rules from the product spec:
--   * Observations and changes are append-only history. Never delete them.
--   * Every numeric claim carries its own evidence and verification level.
--   * A failed source must never mark an offer ENDED (§13).
--   * Token units are stored exactly as published; weighted tokens are not
--     silently converted to tokens (§56).

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------------------
-- Enumerated vocabularies (§6 status, §4 access types, §8 evidence levels)
-- ---------------------------------------------------------------------------

do $$ begin
  create type provider_status as enum (
    'active', 'suspended', 'acquired', 'shut_down'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type offer_status as enum (
    'upcoming', 'live', 'changed', 'ending', 'exhausted',
    'ended', 'suspended', 'unverified'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type offer_type as enum (
    'shared_pool', 'free_tier', 'rotating_free_model', 'sponsored_inference',
    'promotional_event', 'free_credits', 'keyless', 'free_trial', 'ended'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type event_status as enum (
    'upcoming', 'live', 'ended', 'cancelled', 'exhausted'
  );
exception when duplicate_object then null; end $$;

-- Evidence hierarchy (§8). 1 is strongest.
do $$ begin
  create type verification_level as enum (
    'live_api', 'official_docs', 'official_event_page',
    'official_announcement', 'official_social', 'secondary', 'community'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type change_type as enum (
    'new', 'model_added', 'model_removed', 'quota_increased', 'quota_decreased',
    'pool_started', 'pool_exhausted', 'pool_extended', 'pool_cancelled',
    'price_changed', 'card_required', 'card_removed',
    'subscription_required', 'subscription_removed', 'free_tier_started',
    'free_tier_ended', 'rate_limit_changed', 'status_changed'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type source_health as enum (
    'live', 'slow', 'degraded', 'failed', 'stale', 'disabled'
  );
exception when duplicate_object then null; end $$;

do $$ begin
  create type candidate_status as enum (
    'pending', 'verified', 'rejected', 'investigating', 'merged'
  );
exception when duplicate_object then null; end $$;

-- ---------------------------------------------------------------------------
-- providers (§7.1)
-- ---------------------------------------------------------------------------

create table if not exists providers (
  id                bigint generated by default as identity primary key,
  name              text not null,
  slug              text not null unique,
  official_url      text not null,
  logo_url          text,
  description       text,
  provider_type     text,
  country           text,
  status            provider_status not null default 'active',
  -- Denormalised rollups, refreshed by the change detector each sweep.
  free_model_count  int not null default 0,
  live_offer_count  int not null default 0,
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  last_verified_at  timestamptz
);

-- ---------------------------------------------------------------------------
-- sources — the configurable source registry (§10).
-- Adding a provider must not require touching frontend code, so this
-- references providers by slug and is created after it.
-- ---------------------------------------------------------------------------

create table if not exists sources (
  id                bigint generated by default as identity primary key,
  provider_slug     text not null references providers (slug) on delete cascade,
  url               text not null,
  -- json | html | rsc | openapi
  source_type       text not null default 'json',
  priority          int  not null default 5,
  -- Key into the collector registry. Data-driven, never a component import.
  parser_key        text not null,
  enabled           boolean not null default true,
  is_official       boolean not null default true,
  interval_hours    numeric not null default 5,
  last_fetched_at   timestamptz,
  last_ok_at        timestamptz,
  last_status_code  int,
  last_latency_ms   int,
  last_error        text,
  health            source_health not null default 'live',
  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),
  unique (provider_slug, url, parser_key)
);

-- ---------------------------------------------------------------------------
-- models (§7.2)
-- ---------------------------------------------------------------------------

create table if not exists models (
  id                 bigint generated by default as identity primary key,
  provider_id        bigint references providers (id) on delete set null,
  model_id           text not null,
  slug               text not null unique,
  display_name       text not null,
  family             text,
  parameter_count    bigint,
  context_window     int,
  capabilities       text[] not null default '{}',
  official_model_url text,
  first_seen_at      timestamptz not null default now(),
  created_at         timestamptz not null default now(),
  updated_at         timestamptz not null default now(),
  unique (provider_id, model_id)
);

-- ---------------------------------------------------------------------------
-- events — shared pools and promotional events (§7.4)
-- ---------------------------------------------------------------------------

create table if not exists events (
  id                   bigint generated by default as identity primary key,
  provider_id          bigint not null references providers (id) on delete cascade,
  name                 text not null,
  slug                 text not null unique,
  description          text,
  status               event_status not null default 'upcoming',
  start_at             timestamptz,
  end_at               timestamptz,
  pool_size            bigint,
  pool_remaining       bigint,
  -- tokens | weighted_tokens | credits | dollars | neurons
  unit                 text not null default 'tokens',
  models               text[] not null default '{}',
  eligibility          text,
  requirements         text,
  exhaustion_condition text,
  official_url         text,
  announced_at         timestamptz,
  discovered_at        timestamptz not null default now(),
  last_verified_at     timestamptz,
  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- offers (§7.3)
-- ---------------------------------------------------------------------------

create table if not exists offers (
  id                        bigint generated by default as identity primary key,
  provider_id               bigint not null references providers (id) on delete cascade,
  model_id                  bigint references models (id) on delete set null,
  -- The provider's own model identifier, kept verbatim. This is the join key
  -- the sweep reconciles on, because a model may exist before it has a row in
  -- `models` (free credits, keyless routes, pools covering many models).
  model_id_text             text,
  -- Human label for the model when no models row is attached yet.
  model_label               text,
  offer_type                offer_type not null,
  status                    offer_status not null default 'unverified',

  access_requires_account  boolean not null default true,
  access_requires_subscription boolean not null default false,
  payment_required         boolean not null default false,
  card_required            boolean not null default false,
  api_key_required         boolean not null default true,
  keyless                  boolean not null default false,

  compatibility_openai    boolean not null default false,
  compatibility_anthropic boolean not null default false,
  compatibility_other     text,

  -- Quotas are published in the provider's own units (§55, §56).
  -- We never convert between dimensions without explicit documentation.
  rpm                      int,
  rpd                      int,
  tpm                      bigint,
  tpd                      bigint,
  monthly_limit            bigint,
  monthly_unit             text,
  token_limit              bigint,
  token_limit_unit         text,

  pool_size                bigint,
  pool_remaining           bigint,
  pool_unit                text,

  credit_amount            numeric,
  credit_currency          text,

  start_at                 timestamptz,
  end_at                   timestamptz,
  exhaustion_condition     text,

  commercial_use           text,
  data_policy              text,
  retention_policy         text,

  official_evidence_url    text,
  secondary_evidence_url   text,
  verification_level       verification_level not null default 'community',
  confidence               numeric,

  first_discovered_at      timestamptz not null default now(),
  first_verified_at        timestamptz,
  last_verified_at         timestamptz,
  last_seen_live_at        timestamptz,
  ended_at                 timestamptz,
  is_seed_data             boolean not null default false,
  -- sha256 of the normalised payload from the sweep that last wrote this row.
  -- Lets a retried sweep detect "nothing actually changed" without relying on
  -- wall-clock comparison alone (§78 idempotency).
  payload_hash             text,

  created_at               timestamptz not null default now(),
  updated_at               timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- observations — one row per source per sweep. Append-only (§7.5, §67).
-- ---------------------------------------------------------------------------

create table if not exists observations (
  id               bigint generated by default as identity primary key,
  provider_id      bigint references providers (id) on delete cascade,
  offer_id         bigint references offers (id) on delete cascade,
  event_id         bigint references events (id) on delete cascade,
  source_id        bigint references sources (id) on delete set null,
  observed_at      timestamptz not null default now(),
  status           offer_status,
  raw_status       text,
  token_limit      bigint,
  pool_size        bigint,
  pool_remaining   bigint,
  rpm              int,
  rpd              int,
  tpm              bigint,
  tpd              bigint,
  model_count      int,
  source_url       text,
  source_type      text,
  -- sha256 of the normalised payload: makes re-running a sweep idempotent (§78).
  response_hash    text not null,
  raw_payload      jsonb,
  http_status      int,
  latency_ms       int,
  verification_level verification_level,
  created_at       timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- changes — the derived event log (§7.6, §15)
-- ---------------------------------------------------------------------------

create table if not exists changes (
  id           bigint generated by default as identity primary key,
  provider_id  bigint references providers (id) on delete cascade,
  offer_id     bigint references offers (id) on delete cascade,
  event_id     bigint references events (id) on delete cascade,
  change_type  change_type not null,
  field        text,
  old_value    text,
  new_value    text,
  detected_at  timestamptz not null default now(),
  effective_at timestamptz,
  source_url   text,
  evidence     text,
  severity     text not null default 'info',
  -- Hash of (change_type, field, old, new, subject) within a window, so a
  -- retried sweep does not duplicate history (§78).
  dedupe_key   text
);

-- ---------------------------------------------------------------------------
-- sweep_runs — one row per monitoring cycle (§11, §79)
-- ---------------------------------------------------------------------------

create table if not exists sweep_runs (
  id                bigint generated by default as identity primary key,
  started_at        timestamptz not null default now(),
  finished_at       timestamptz,
  duration_ms       int,
  sources_total     int not null default 0,
  sources_ok        int not null default 0,
  sources_failed    int not null default 0,
  offers_new        int not null default 0,
  offers_changed    int not null default 0,
  offers_ended      int not null default 0,
  changes_created   int not null default 0,
  trigger           text not null default 'cron',
  errors            jsonb
);

-- ---------------------------------------------------------------------------
-- discovery_candidates — admin review queue (§52)
-- ---------------------------------------------------------------------------

create table if not exists discovery_candidates (
  id             bigint generated by default as identity primary key,
  url            text not null,
  provider_guess text,
  note           text,
  discovered_from text,
  discovered_at  timestamptz not null default now(),
  status         candidate_status not null default 'pending',
  classification jsonb,
  evidence       text,
  reviewed_at    timestamptz,
  is_seed_data   boolean not null default false
);

-- ---------------------------------------------------------------------------
-- source_conflicts — §54. Both readings are stored; neither is chosen.
-- ---------------------------------------------------------------------------

create table if not exists source_conflicts (
  id             bigint generated by default as identity primary key,
  provider_id    bigint references providers (id) on delete cascade,
  offer_id       bigint references offers (id) on delete cascade,
  field          text not null,
  value_a        text,
  source_a       text,
  value_b        text,
  source_b       text,
  detected_at    timestamptz not null default now(),
  resolved_at    timestamptz
);

-- ---------------------------------------------------------------------------
-- Indexes (§69)
-- ---------------------------------------------------------------------------

create index if not exists idx_sources_provider        on sources (provider_slug);
create index if not exists idx_sources_enabled        on sources (enabled) where enabled;
create index if not exists idx_offers_status          on offers (status);
create index if not exists idx_offers_provider        on offers (provider_id);
create index if not exists idx_offers_model           on offers (model_id);
create index if not exists idx_offers_model_text      on offers (provider_id, model_id_text);
create index if not exists idx_offers_live            on offers (status) where status in ('live','changed','ending');
create index if not exists idx_offers_last_verified   on offers (last_verified_at desc nulls last);
create index if not exists idx_offers_start           on offers (start_at desc nulls last);
create index if not exists idx_offers_end             on offers (end_at desc nulls last);
create index if not exists idx_offers_type            on offers (offer_type);
create index if not exists idx_offers_cardless        on offers (card_required) where card_required = false;
create index if not exists idx_models_provider        on models (provider_id);
create index if not exists idx_events_status          on events (status);
create index if not exists idx_events_start           on events (start_at desc nulls last);
create index if not exists idx_changes_detected       on changes (detected_at desc);
create index if not exists idx_changes_type           on changes (change_type);
create index if not exists idx_changes_offer          on changes (offer_id, detected_at desc);
create index if not exists idx_observations_observed   on observations (observed_at desc);
create index if not exists idx_observations_provider  on observations (provider_id, observed_at desc);
create index if not exists idx_observations_response  on observations (response_hash);
create unique index if not exists uq_changes_dedupe    on changes (dedupe_key) where dedupe_key is not null;
create index if not exists idx_providers_slug         on providers (slug);
create index if not exists idx_candidates_status      on discovery_candidates (status);

-- ---------------------------------------------------------------------------
-- updated_at maintenance
-- ---------------------------------------------------------------------------

create or replace function touch_updated_at() returns trigger
language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end $$;

do $$
declare t text;
begin
  foreach t in array array['providers','models','offers','events','sources']
  loop
    execute format(
      'drop trigger if exists trg_%1$s_touch on %1$I;', t);
    execute format(
      'create trigger trg_%1$s_touch before update on %1$I
         for each row execute function touch_updated_at();', t);
  end loop;
end $$;

-- ---------------------------------------------------------------------------
-- Freshness (§14) — computed in SQL so every surface agrees.
-- ---------------------------------------------------------------------------

create or replace view offer_freshness as
select
  o.id,
  case
    when o.last_verified_at is null                    then 'unverified'
    when now() - o.last_verified_at < interval '6 hours'   then 'fresh'
    when now() - o.last_verified_at < interval '24 hours'  then 'aging'
    when now() - o.last_verified_at < interval '72 hours'  then 'stale'
    else 'very_stale'
  end as freshness
from offers o;

comment on column offers.token_limit_unit is
  'Unit exactly as published: tokens | weighted_tokens | requests | credits | neurons. Never converted.';
comment on column offers.pool_unit is
  'Unit for pool_size/pool_remaining, kept verbatim from the provider.';
comment on table observations is
  'Append-only. One row per source per sweep; retained permanently.';
comment on table changes is
  'Append-only change log. dedupe_key makes a retried sweep idempotent.';
