-- ==================================================================
-- 0010_candidate_decisions.sql
-- ------------------------------------------------------------------
-- The discovery queue was losing history.
--
-- rpc_resolve_candidate stores one resolution_note per candidate, so a second
-- review overwrites the first. That is the same defect as the change feed that
-- showed four identical rows: the data is fine, but the record of what was
-- decided and why has been flattened into whatever happened most recently.
--
-- For this product it matters more than usual. §16 keeps history permanently
-- and §3 forbids silently deleting things. A reviewer who rejects a bad lead
-- is doing the work that stops the next reviewer re-reading it, and that work
-- is worth exactly nothing if the reason disappears the moment someone reopens
-- the candidate.
--
-- So every transition is appended to a decisions log, and resolution_note is
-- demoted to what it honestly is: the note attached to the current status.
-- ==================================================================

begin;

create table if not exists discovery_candidate_decisions (
  id                 bigint generated by default as identity primary key,
  candidate_id       bigint not null references discovery_candidates (id) on delete cascade,
  from_status        candidate_status,
  to_status          candidate_status not null,
  note               text,
  into_provider_id   bigint,
  into_offer_id      bigint,
  decided_at         timestamptz not null default now()
);

comment on table discovery_candidate_decisions is
  'Append-only log of every review decision on a discovery candidate (A52).';

create index if not exists idx_candidate_decisions
  on discovery_candidate_decisions (candidate_id, decided_at desc);

-- ------------------------------------------------------------------
-- Rewrite the resolver to append rather than overwrite.
-- ------------------------------------------------------------------

create or replace function rpc_resolve_candidate(
  p_candidate_id  bigint,
  p_status        candidate_status,
  p_note          text   default null,
  p_into_provider bigint  default null,
  p_into_offer    bigint  default null
) returns discovery_candidates
language plpgsql
security definer
set search_path = public
as $$
declare
  v_candidate discovery_candidates;
  v_from      candidate_status;
begin
  if p_status is null then
    raise exception 'rpc_resolve_candidate: status is required'
      using errcode = '22004';
  end if;

  select * into v_candidate from discovery_candidates where id = p_candidate_id for update;
  if not found then
    raise exception 'rpc_resolve_candidate: candidate % does not exist', p_candidate_id
      using errcode = 'P0002';
  end if;

  v_from := v_candidate.status;

  if p_status = 'merged' and p_into_provider is null and p_into_offer is null then
    raise exception 'rpc_resolve_candidate: a merge must name the provider or offer it merged into'
      using errcode = '22004';
  end if;

  if p_status in ('verified', 'rejected') and coalesce(trim(p_note), '') = '' then
    raise exception 'rpc_resolve_candidate: % requires a note explaining the decision',
      p_status
      using errcode = '22004';
  end if;

  -- A transition that changes neither the status nor the note records nothing,
  -- and would make the log harder to read than the thing it records. Repeating
  -- the status with a *different* note is legitimate — that is a reviewer
  -- reporting what they found while the candidate stayed open — so the note is
  -- part of the comparison rather than an exemption from it.
  if v_from = p_status
     and coalesce(trim(p_note), '') = coalesce(trim(v_candidate.resolution_note), '') then
    raise exception 'rpc_resolve_candidate: candidate % is already % with that note',
      p_candidate_id, p_status
      using errcode = '22004';
  end if;

  -- The log entry is written first, so a failure in the update cannot leave a
  -- status changed with no recorded reason.
  insert into discovery_candidate_decisions (
    candidate_id, from_status, to_status, note,
    into_provider_id, into_offer_id
  ) values (
    p_candidate_id, v_from, p_status, p_note,
    case when p_status = 'merged' then p_into_provider else null end,
    case when p_status = 'merged' then p_into_offer    else null end
  );

  update discovery_candidates
     set status           = p_status,
         resolution_note  = p_note,
         into_provider_id = case when p_status = 'merged' then p_into_provider else null end,
         into_offer_id    = case when p_status = 'merged' then p_into_offer    else null end,
         reviewed_at      = case when p_status = 'investigating' then null else now() end
   where id = p_candidate_id
  returning * into v_candidate;

  return v_candidate;
end;
$$;

comment on function rpc_resolve_candidate is
  'Records a review decision and appends it to the decision log. Never deletes.';

-- ------------------------------------------------------------------
-- Grants. Same posture as 0009: internal routes only.
-- ------------------------------------------------------------------

revoke all on discovery_candidate_decisions from anon, authenticated;
grant select on discovery_candidate_decisions to service_role;
grant execute on function rpc_resolve_candidate(bigint, candidate_status, text, bigint, bigint)
  to service_role;

commit;

select pg_notify('pgrst', 'reload schema');
