-- ==================================================================
-- 0013_admin_login_throttle.sql
-- ------------------------------------------------------------------
-- CIP-002: the admin sign-in had no brute-force throttle.
--
-- A naive in-memory Map does not work here: this runs on Vercel
-- serverless, where each instance has its own memory and an attacker
-- simply spreads attempts across instances. A throttle that appears to
-- work locally and does nothing in production is worse than none.
--
-- So attempt state lives in Postgres, next to everything else the
-- product must not lose. Two small SECURITY DEFINER RPCs own all
-- access; the table itself is revoked from anon/authenticated and
-- granted to service_role only. Internal routes already use the
-- secret key, so the login action can call these without widening
-- any public read.
--
-- Additive only: creates one table and two functions. Alters,
-- drops or touches nothing existing, and never touches
-- discovery_candidate_decisions or any append-only log.
-- ==================================================================

begin;

create table if not exists admin_login_attempts (
  id           bigint generated by default as identity primary key,
  ip           text not null,
  attempted_at timestamptz not null default now(),
  succeeded    boolean not null default false
);

comment on table admin_login_attempts is
  'Failed and successful admin sign-in attempts per client IP (CIP-002). Backing store for the serverless-safe login throttle.';

create index if not exists idx_login_attempts_ip_time
  on admin_login_attempts (ip, attempted_at desc);

-- ------------------------------------------------------------------
-- Row Level Security. This table holds the IP addresses and timing of
-- admin login attempts, so it must never be readable through PostgREST
-- with the anonymous key: an attacker could otherwise enumerate exactly
-- when and from where the admin account is being targeted. RLS is
-- enabled and both anon and authenticated are denied select explicitly
-- (USING (false)); all access goes through the SECURITY DEFINER RPCs
-- below, called with the secret key, and service_role bypasses RLS.
-- ------------------------------------------------------------------

alter table admin_login_attempts enable row level security;

drop policy if exists deny_anon_read_login_attempts on admin_login_attempts;
create policy deny_anon_read_login_attempts on admin_login_attempts
  for select to anon using (false);

drop policy if exists deny_authenticated_read_login_attempts on admin_login_attempts;
create policy deny_authenticated_read_login_attempts on admin_login_attempts
  for select to authenticated using (false);

-- ------------------------------------------------------------------
-- Record one attempt. Prunes rows older than 24h so the table stays
-- small without a scheduled job.
-- ------------------------------------------------------------------

create or replace function rpc_record_login_attempt(
  p_ip      text,
  p_success boolean default false
) returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if coalesce(trim(p_ip), '') = '' then
    raise exception 'rpc_record_login_attempt: ip is required'
      using errcode = '22004';
  end if;

  insert into admin_login_attempts (ip, attempted_at, succeeded)
  values (p_ip, now(), coalesce(p_success, false));

  delete from admin_login_attempts
   where attempted_at < now() - interval '24 hours';
end;
$$;

comment on function rpc_record_login_attempt(text, boolean) is
  'Records one admin sign-in attempt and prunes entries older than 24h (CIP-002).';

-- ------------------------------------------------------------------
-- True when the IP has failed at least p_max_attempts times inside
-- the last p_window_minutes minutes. Successes never count.
-- ------------------------------------------------------------------

create or replace function rpc_login_blocked(
  p_ip             text,
  p_max_attempts   integer default 10,
  p_window_minutes integer default 15
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_fails integer;
begin
  if coalesce(trim(p_ip), '') = '' then
    return false;
  end if;

  select count(*) into v_fails
    from admin_login_attempts
   where ip = p_ip
     and succeeded = false
     and attempted_at > now() - (make_interval(mins => greatest(p_window_minutes, 1)));

  return coalesce(v_fails, 0) >= greatest(p_max_attempts, 1);
end;
$$;

comment on function rpc_login_blocked(text, integer, integer) is
  'True when an IP exhausted its failed admin-login budget inside the window (CIP-002).';

-- ------------------------------------------------------------------
-- Grants. Same posture as the discovery queue: internal only.
-- ------------------------------------------------------------------

revoke all on admin_login_attempts from anon, authenticated;
grant select, insert, delete on admin_login_attempts to service_role;
grant execute on function rpc_record_login_attempt(text, boolean) to service_role;
grant execute on function rpc_login_blocked(text, integer, integer) to service_role;

commit;

select pg_notify('pgrst', 'reload schema');
